name: "📄 Extract ChatGPT Conversation"
description: Extract conversations from ChatGPT share links and generate a GitHub page automatically.
title: "ChatGPT Conversation Extraction Request"
labels: ["extraction"]
body:
  - type: markdown
    attributes:
      value: |
        **Thanks for sharing your ChatGPT conversation!** We’d love to help you extract this chat and generate a GitHub page from it. 

        Please paste the share link below so we can get started!

  - type: input
    id: chatgpt-share-link
    attributes:
      label: Your ChatGPT Share Conversation Link
      placeholder: "https://chatgpt.com/share/blahblahblah"
    validations:
      required: true
