name: Extract ChatGPT Conversation

on:
  issues:
    types: [labeled]

jobs:
  extract-conversation:
    if: contains(github.event.label.name, 'extraction')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # Assuming you use requests to fetch content

      - name: Extract ChatGPT conversation
        run: |
          # Extract the share link from the issue body
          export SHARE_LINK=$(echo "${{ github.event.issue.body }}" | grep -oP 'https://chatgpt.com/share/\S+')

          # Run the Python main to fetch and process the conversation
          python main.py --share-link "$SHARE_LINK"

      - name: Commit Markdown file
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add collection/
          git commit -m "Add ChatGPT conversation from $SHARE_LINK"
          git push

      # Step to add "done" label to the issue
      - name: Label issue as "done"
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "done"
        continue-on-error: true # Ensure the workflow continues even if the label fails to apply

      # Step to close the issue
      - name: Close issue
        run: |
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
            -d '{"state": "closed"}'
