name: Extract ChatGPT Conversation

on:
  issues:
    types: [labeled]

jobs:
  extract-conversation:
    if: contains(github.event.label.name, 'extraction') # Run only if the "extraction" label is added
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # Assuming you use requests to fetch content

      - name: Extract ChatGPT conversation
        id: extract_conversation
        run: |
          # Extract the share link from the issue body
          SHARE_LINK=$(echo "${{ github.event.issue.body }}" | grep -oP 'https://chatgpt.com/share/\S+')

          # Run Python script with the share link
          python main.py --share-link "$SHARE_LINK"
        continue-on-error: true # Ensure workflow doesn't fail even if extraction fails

      - name: Commit Markdown file
        if: success() && steps.extract_conversation.conclusion == 'success'
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add collection/
          git commit -m "Add ChatGPT conversation from issue #${{ github.event.issue.number }}"
          git push

      - name: Label issue as "done"
        if: steps.extract_conversation.conclusion == 'success'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "done"
        continue-on-error: true

      - name: Label issue as "failed"
        if: steps.extract_conversation.conclusion != 'success'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "failed"

      - name: Close issue
        run: |
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
            -d '{"state": "closed"}'
